### ISSUE TITLE
Exception is raised whenever you try to download with a different user/password

### ISSUE THREAD

**Issue by CharlieCorner** [CharlieCorner/pymage_downloader#1]
After successfully using pymage with a user/pass, changing the user/pass to download from another account raises the following exception:
```304
Traceback (most recent call last):
  File "pymage_downloader.py", line 226, in <module>
    main()
  File "pymage_downloader.py", line 34, in main
    process_posts(submissions, args)
  File "pymage_downloader.py", line 71, in process_posts
    for post in submissions:
  File "/home/username/.local/lib/python3.5/site-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/home/username/.local/lib/python3.5/site-packages/praw/models/listing/generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/username/.local/lib/python3.5/site-packages/praw/reddit.py", line 367, in get
    data = self.request('GET', path, params=params)
  File "/home/username/.local/lib/python3.5/site-packages/praw/reddit.py", line 472, in request
    params=params)
  File "/home/username/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 175, in request
    params=params, url=url)
  File "/home/username/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 109, in _request_with_retries
    data, files, json, method, params, retries, url)
  File "/home/username/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 94, in _make_request
    params=params)
  File "/home/username/.local/lib/python3.5/site-packages/prawcore/rate_limit.py", line 32, in call
    kwargs['headers'] = set_header_callback()
  File "/home/username/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 135, in _set_header_callback
    self._authorizer.refresh()
  File "/home/username/.local/lib/python3.5/site-packages/prawcore/auth.py", line 328, in refresh
    password=self._password)
  File "/home/username/.local/lib/python3.5/site-packages/prawcore/auth.py", line 142, in _request_token
    payload.get('error_description'))
prawcore.exceptions.OAuthException: invalid_grant error processing request
```

**Comment by CharlieCorner** [comment]
This is due to how PyMage was registered to be used. For development purposes, this was registered as a Script Application for which Reddit requires that all users be explicitly registered on the application registration.

This is also an example of why people that want to use PyMage's code base should register their own app with Reddit along with creating a custom user-agent string to be used inside of praw.ini
